USE [master]
GO

CREATE DATABASE [david_rodriguez]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'david_rodriguez', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\david_rodriguez.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'david_rodriguez_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\david_rodriguez_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [david_rodriguez].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [david_rodriguez] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [david_rodriguez] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [david_rodriguez] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [david_rodriguez] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [david_rodriguez] SET ARITHABORT OFF 
GO

ALTER DATABASE [david_rodriguez] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [david_rodriguez] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [david_rodriguez] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [david_rodriguez] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [david_rodriguez] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [david_rodriguez] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [david_rodriguez] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [david_rodriguez] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [david_rodriguez] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [david_rodriguez] SET  DISABLE_BROKER 
GO

ALTER DATABASE [david_rodriguez] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [david_rodriguez] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [david_rodriguez] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [david_rodriguez] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [david_rodriguez] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [david_rodriguez] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [david_rodriguez] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [david_rodriguez] SET RECOVERY FULL 
GO

ALTER DATABASE [david_rodriguez] SET  MULTI_USER 
GO

ALTER DATABASE [david_rodriguez] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [david_rodriguez] SET DB_CHAINING OFF 
GO

ALTER DATABASE [david_rodriguez] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [david_rodriguez] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [david_rodriguez] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [david_rodriguez] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [david_rodriguez] SET QUERY_STORE = ON
GO

ALTER DATABASE [david_rodriguez] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [david_rodriguez] SET  READ_WRITE 
GO


